
export const UploadfileUrl = '/upload-file'
export const RegisterUrl = '/register'
export const LoginUrl = '/login'
export const SetHeadImgUrl = '/set-head-img'
export const GetVerificationCodeUrl = '/get-verification-code'
export const VerificationCodeUrl = '/verification-code'
export const IdentitySearchUrl = '/identity-search'
export const AddFriendUrl = '/add-friend'
export const DeleteFriendUrl = '/delete-friend'
export const GetChatFriendsUrl = '/get-chat-friends'
export const GetGroupChatsUrl = '/get-group-chats'
export const CreateGroupChatUrl = '/create-group-chat'
export const GroupChatAddMemberUrl = '/groupchat-add-member'
export const SetGroupChatNameUrl = '/set-groupchat-name'
export const ExitGroupChatUrl = '/exit-groupchat'
export const SearchGroupChatUrl = '/search-groupChat'
export const JoinGroupChatUrl = '/join-groupChat'