
const baseUrl = 'http://localhost:888'

export const UploadfileUrl = baseUrl + '/upload-file'
export const SocketIoChatUrl = baseUrl + '/chat'
export const RegisterUrl = baseUrl + '/register'
export const LoginUrl = baseUrl + '/login'
export const SetHeadImgUrl = baseUrl + '/set-head-img'
export const GetVerificationCodeUrl = baseUrl + '/get-verification-code'
export const VerificationCodeUrl = baseUrl + '/verification-code'
export const IdentitySearchUrl = baseUrl + '/identity-search'
export const AddFriendUrl = baseUrl + '/add-friend'
export const DeleteFriendUrl = baseUrl + '/delete-friend'
export const GetChatFriendsUrl = baseUrl + '/get-chat-friends'
export const GetGroupChatsUrl = baseUrl + '/get-group-chats'
export const CreateGroupChatUrl = baseUrl + '/create-group-chat'
export const GroupChatAddMemberUrl = baseUrl + '/groupchat-add-member'
export const SetGroupChatNameUrl = baseUrl + '/set-groupchat-name'
export const ExitGroupChatUrl = baseUrl + '/exit-groupchat'
export const SearchGroupChatUrl = baseUrl + '/search-groupChat'
export const JoinGroupChatUrl = baseUrl + '/join-groupChat'