
export const TEST = 'test'

export const INIT_STATE = 'init_state'
export const RESET_STARE = 'reset_stare'
export const INIT_USER = 'init_user'
export const UPDATE_USER = 'update_user'
export const PUSH_NEWFRIEND = 'push_newFriend'
export const PUSH_FRIEND = 'push_friend'
export const REMOVE_FRIEND = 'remove_friend'
export const PUSH_CHAT = 'push_chat'
export const SET_CHAT = 'set_chat'
export const REMOVE_CHAT = 'remove_chat'
export const UPDATE_CHATS = 'update_chats'
export const UPDATE_CHAT_MSG = 'update_chat_msg'
export const REMOVE_NEWFRIEND = 'remove_newFrient'
export const SET_CURRENT_CHAT = 'set_current_chat'
export const PUSH_GROUPCHAT = 'push_groupChat'
export const GROUPCHAT_ADD_MEMBER = 'groupChat_add_member'
export const SET_GROUPCHAT_NAME = 'set_groupchat_name'
export const REMOVE_GROUPCHAT = 'remove_groupchat'
export const GROUPCHAT_REMOVE_MEMBER = 'groupChat_REMOVE_member'
export const SET_HAVE_READ = 'set_have_read'
export const ADD_NO_PROMPT_LIST = 'add_no_prompt_list'
export const POP_NO_PROMPT_LIST = 'pop_no_prompt_list'
export const UPDATE_WITHDRAWN_THE_MSG = 'update_withdrawn_the_msg'//更新撤回的消息,没有什么实际作用,只是用于通过更新来刷新界面(通过刷新界面来取消文字信息的撤回后的重新编辑功能,因为重新编辑设置了时效)
export const REMOVE_MSG = 'remove_msg'
